$('.owl-carousel').owlCarousel({
    loop:true,
    margin:50,
    dots:false,
    // nav:true,
    smartSpeed:700,
    responsiveClass:true,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:1
        },
        1000:{
            items:1
        }
    }
})